---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  #This defines which pods are going to be represented by this service
  selector:
    app: webapp #same keypair we adedd in metadata
  ports:
    - name: http
      port: 80
      #targetPort: 80
      nodePort: 30080
  type: NodePort
